public class Constants {
	//TODO - move to label
	public static final String LIMIT_LOGGER_MAX_ONCE_START_EXCEPTION = 'Exceptions can be stopped at most one time. This Limit Log has already been stopped';
	public static final String LIMIT_LOGGER_MAX_ONCE_STOP_EXCEPTION = 'Exceptions can be start at most one time. This Limit Log has already been started';
	public static final String DML_INSERT = 'Insert';
	public static final String DML_UPDATE = 'Update';
	public static final String DML_DELETE = 'Delete';
	public static final String DML_UNDELETE = 'Undelete';
}